# metadata file

name: Meterian Scanner
description: Scan your repository for vulnerabilities
inputs:
    cli_args:
        required: false
        description: Meterian client parameters.
    oss:
        required: false
        description: Open Source Software flag to instruct the client to avoid authenticating the scan as the project being scanned is open source.
        default: false
    autofix_security:
        required: false
        description: What reach to use to update vulnerable dependencies
    autofix_stability:
        required: false
        description: What reach to use to update outdated dependencies
    autofix_with_pr:
        required: false
        description: Flag to instruct whether a pull request should be opened as a result of the autofix
    autofix_with_issue:
        required: false
        description: Flag to instruct whether an issue should be opened as a result of the autofix
    autofix_with_report:
        required: false
        description: Flag to instruct whether a pull request also including a PDF report should be opened as a result of the autofix

runs:
    using: docker
    image: Dockerfile
    args: 
        - ${{ inputs.cli_args }}
        - ${{ inputs.oss }}
        - ${{ inputs.autofix }}
        - ${{ inputs.autofix_pr_branches }}
        - ${{ inputs.autofix_issue_branches }}
branding: 
    icon: zoom-in
    color: blue