# metadata file

name: Meterian Scanner
description: Scan your repository for vulnerabilities
inputs:
    cli_args:
        required: false
        description: Meterian client parameters
runs:
    using: docker
    image: Dockerfile
    args: 
        - ${{ inputs.cli_args }}
branding: 
    icon: zoom-in
    color: blue