# metadata file

name: Meterian Scanner
description: Scan your repository for vulnerabilities
inputs:
    cli_args:
        required: false
        description: Meterian client parameters
    oss:
        required: false
        description: Open Source Software flag
        default: false
runs:
    using: docker
    image: Dockerfile
    args: 
        - ${{ inputs.cli_args }}
        - ${{ inputs.oss }}
branding: 
    icon: zoom-in
    color: blue