# manifest

# action.yml

name: Meterian Scanner
description: Scan a Java repository for vulnerabilities in your project  
inputs:
    cli_args:
        required: false
        description: Meterian client parameters
outputs: 
    exit_code:
        description: The exit code returned by the Meterian client reflecting the scan outcome
runs:
    using: docker
    image: Dockerfile
    args: 
        - ${{ inputs.cli_args }}
branding: 
    icon: zoom-in
    color: blue